---
- name: Configure Coder development server
  hosts: coder
  become: true
  roles:
    - system
    - ufw
    - docker
    - sysbox
    - mosh
    - coder
    - role: monitoring
      tags: [monitoring]
